name: "Advanced Git Sync"
description: "Synchronize GitHub repository with GitLab including branches, PRs, and issues"
author: "vikshan"

inputs:
  gitlab_url:
    description: "GitLab instance URL"
    required: true
  gitlab_token:
    description: "GitLab Personal Access Token"
    required: true
  gitlab_username:
    description: "GitLab username"
    required: true
  config_path:
    description: "Path to the sync configuration file"
    required: false
    default: ".github/git-sync.yml"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: |
        bun install

    - name: Build and run
      shell: bash
      run: |
        bun build ./src/index.ts --outfile=dist/index.js
        bun run dist/index.js

branding:
  icon: "git-branch"
  color: "orange"
