name: "Advanced Git Sync"
description: "Synchronize GitHub repository with GitLab including branches, PRs, and issues"
author: "vikshan"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication (use GH_TOKEN secret for workflow scope)"
    required: false
    default: ${{ github.token }}

  GH_TOKEN:
    description: "GitHub Personal Access Token with workflow scope (recommended)"
    required: false

  GITLAB_TOKEN:
    description: "GitLab token for authentication"
    required: false

  CONFIG_PATH:
    description: "Path to the sync configuration file"
    required: false
    default: ".github/sync-config.yml"

runs:
  using: "composite"
  steps:
    - name: Setup Bun and install dependencies
      uses: iamvikshan/.github/.github/actions/bun-actions@main
      with:
        working-directory: ${{ github.action_path }}

    - name: Run Advanced Git Sync
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.GH_TOKEN || inputs.GITHUB_TOKEN }}
        INPUT_GITLAB_TOKEN: ${{ inputs.GITLAB_TOKEN }}
        INPUT_CONFIG_PATH: ${{ inputs.CONFIG_PATH }}
      run: bun run ${{ github.action_path }}/src/index.ts

branding:
  icon: "git-branch"
  color: "orange"
